/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_i_gpiotb_jni_JniUtil */

#ifndef _Included_com_example_i_gpiotb_jni_JniUtil
#define _Included_com_example_i_gpiotb_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_i_gpiotb_jni_JniUtil
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_i_gpiotb_jni_JniUtil_getJniString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_i_gpiotb_jni_JniUtil
 * Method:    writeStderr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_i_gpiotb_jni_JniUtil_writeStderr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
